version: "3.9"

services:
  invoice-analyzer:
    build: .
    ports:
      - "8036:8036"
    environment:
      - API_KEY=${API_KEY}           # For your Gemini API key
      - GEMINI_MODEL=${GEMINI_MODEL}           # For your Gemini Model
    volumes:
      - .:/app
    restart: unless-stopped
